version: '3.8'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - kiosk

  kiosk:
    restart: always
    build:
      context: ./kiosk
    ports:
      - 5004:5004
    expose:
      - 5004
    depends_on:
      - react

  react:
    restart: always
    build:
      context: ./react
    ports:
      - 5001:5001
    expose:
      - 5001
    depends_on:
      - aligo


  aligo:
    restart: always
    build:
      context: ./aligo
    ports:
      - 8100:8000
    expose:
      - 8100
    volumes:
      - ./logs:/app/logs
    depends_on:
      - node

  node:
    restart: always
    build:
      context: ./node
    ports:
      - 5002:5002
    expose:
      - 5002
    depends_on:
      - mysql
      

  mysql:
    restart: unless-stopped
    build:
      context: ./mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log.cnf:/etc/mysql/conf.d/log.cnf:ro
      - ./mysql/logs:/var/log/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci